const workTime = localStorage.getItem('work-time')
const breakTime = localStorage.getItem('break-time')
const longBreakTime = localStorage.getItem('long-break-time')
export const initialTime = workTime ? (Number(workTime) * 60) : (25 * 60)
export const initialBreak = breakTime ? (Number(breakTime) * 60) : (10 * 60)
export const initialLongBreak = longBreakTime ? (Number(longBreakTime) * 60) : (30 * 60)
